framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

        envelope:
            sender: 'callistusnkamuo@gmail.com'
            # recipients: ['foo@example.com', 'bar@example.com']
        headers:
            From: 'Callistus Nkamuo <callistusnkamuo@gmail.com>'
            # Bcc: 'baz@example.com'
            # X-Custom-Header: 'foobar'