framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

        envelope:
            sender: 'order@electrodiscount.be'
        headers:
            From: 'Order Planning <order@electrodiscount.be>'
            # Bcc: 'baz@example.com'
            # X-Custom-Header: 'foobar'