framework:
    workflows:
        shipment_operation:
            # type: "workflow" # or 'state_machine'
            type: "state_machine" # or 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: "method"
                property: "status"
            supports:
                - App\Entity\Shipment\Shipment
            initial_marking: new
            places:
                - new
                - assigned
                - processing
                - ready
                - intransit
                - delivered
                - completed
                - cancelled
                - onhold
            transitions:
                assigned:
                    from: new
                    to: assigned
                processing:
                    from: assigned
                    to: processing
                ready:
                    from: [assigned, processing]
                    to: ready

                intransit:
                    from: [processing, ready]
                    to: intransit
                delivered:
                    from: [ready, intransit]
                    to: delivered
                completed:
                    from: delivered
                    to: completed

                cancelled:
                    from: [new, assigned]
                    to: cancelled

                onhold:
                    from: [new, assigned, processing, ready, intransit]
                    to: onhold
